name: Backend CI

on:
  push:
    paths: ["backend/**"]
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --working-dir=backend

      - name: Generate key
        run: php backend/artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage backend/bootstrap/cache

      - name: Install npm packages
        run: npm install --error --working-dir=backend

      - name: Create Database
        run: |
          mkdir -p backend/database
          touch backend/database/database.sqlite

      - name: Run Code Format
        run: backend/vendor/bin/pint --preset=laravel --verbose

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: backend/database/database.sqlite
        run: backend/vendor/bin/phpunit

      - name: Check for formatting changes
        run: git diff --exit-code || echo "Formatting changes detected."

      - name: Commit and push changes if any
        if: success() && steps.check-for-formatting-changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Apply Pint code formatting'
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_HOOK_TOKEN }}
